import 'musicdata_model.dart';

class SongsList {
  static List allSongs = const [
    MusicModel(
      name: "Dead inside",
      year: "2020",
      imageUrl: "assets/images/Rectangle 32.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Alone",
      year: "2023",
      imageUrl: "assets/images/272cf15a08dcca3bd22e258e7635e9c2 1.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Dark night",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Joker BGM",
      year: "2020",
      imageUrl: "assets/images/s9.jpg",
      description: "Easy Living",
      songUrl: "music/Jokerbgm.mp3",
    ),
    MusicModel(
      name: "Showdo samuray",
      year: "2023",
      imageUrl: "assets/images/s6.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/LuciferBeliever.mp3",
      year: "2023",
      imageUrl: "assets/images/s10.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Money Heist Le Casa De Papel",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s11.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/LuciferBeliever.mp3",
      year: "2023",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s11.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dark night",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Joker BGM",
      year: "2020",
      imageUrl: "assets/images/s9.jpg",
      description: "Easy Living",
      songUrl: "music/Jokerbgm.mp3",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/s5.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s3.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/s6.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 32.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/272cf15a08dcca3bd22e258e7635e9c2 1.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
    ),
  ];
  static List discographyItem = const [
    MusicModel(
      name: "Dead inside",
      year: "2020",
      imageUrl: "assets/images/Rectangle 32.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Alone",
      year: "2023",
      imageUrl: "assets/images/272cf15a08dcca3bd22e258e7635e9c2 1.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Dark night",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Joker BGM",
      year: "2020",
      imageUrl: "assets/images/s9.jpg",
      description: "Easy Living",
      songUrl: "music/Jokerbgm.mp3",
    ),
    MusicModel(
      name: "Showdo samuray",
      year: "2023",
      imageUrl: "assets/images/s6.png",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Lucifer BGM",
      songUrl: "music/LuciferBeliever.mp3",
      year: "2023",
      imageUrl: "assets/images/s10.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Money Heist Le Casa De Papel",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s11.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/LuciferBeliever.mp3",
      year: "2023",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/s5.jpg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dark night",
      year: "2020",
      imageUrl: "assets/images/s4.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "pirates of the caribbean burning",
      year: "2023",
      imageUrl: "assets/images/s8.jpg",
      description: "Easy Living",
      songUrl: "music/Pirates Of The Caribbean.mp3",
    ),
    MusicModel(
      name: "Joker BGM",
      year: "2020",
      imageUrl: "assets/images/s9.jpg",
      description: "Easy Living",
      songUrl: "music/Jokerbgm.mp3",
    ),
  ];

  static List popularSingleItem = const [
    MusicModel(
      name:
          "We Are Chaos assets/images/Rectangle 34.png assets/images/Rectangle 34.png",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Smile",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "We Are Chaos",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/p1.jpeg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
  ];

  static List favarateSongs = const [
    MusicModel(
      name:
          "We Are Chaos  Chaos assets/images/Rectangle 34.png assets/images/Rectangle 34.png",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Smile",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "We Are Chaos",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/p1.jpeg",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "Dead inside",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Alone",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name:
          "We Are Chaos  Chaos assets/images/Rectangle 34.png assets/images/Rectangle 34.png",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Smile",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "We Are Chaos",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/p1.jpeg",
      description: "Easy Living",
    ),
    MusicModel(
      name:
          "We Are Chaos  Chaos assets/images/Rectangle 34.png assets/images/Rectangle 34.png",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/Rectangle 34.png",
      description: "Easy Living",
    ),
    MusicModel(
      name: "Smile",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2023",
      imageUrl: "assets/images/Rectangle 38.png",
      description: "Berredchild",
    ),
    MusicModel(
      name: "We Are Chaos",
      songUrl: "music/Pirates Of The Caribbean.mp3",
      year: "2020",
      imageUrl: "assets/images/p1.jpeg",
      description: "Easy Living",
    ),
  ];
}
